runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

env_variables:
  APP_ENV: production
  GA_TRACKING_ID: UA-83133303-1
  MAILGUN_DOMAIN: mailgun.premier-pump.io
  MAILGUN_SVALUE: YTJWNUxXUmpOamhpTXpBMFpUQmxNV1U1WmpVMk1tSXpNR05rWXpZMVpqWm1ZakpoCg

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
